### ISSUE TITLE
Rename taskNames under taskLists to taskAliases

### ISSUE THREAD

**Issue by leventogut** [leventogut/xec#1]
```yaml
taskLists:
  - alias: lsenv
    description: "tasklist for ls and env"
    taskNames:
      - ls
      - printenv
```
