### ISSUE TITLE
importing configurations

### ISSUE THREAD

**Issue by leventogut** [leventogut/xec#2]
You should be able to import other xec files under a alias/context name.

```yaml
tasks:
  - alias: k
    description: Kubernetes tasks.
    import: ~/.xec/skills/xec-kubernetes.yaml
```
